linters-settings:
  errcheck:
    check-type-asserts: true
    check-blank: true
    ignore: io:^Copy.*
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen
        - paralleltest
        - forbidigo
