linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io.Copy
  misspell:
    locale: US
  tagliatelle:
    case:
      rules:
        json: snake
  ireturn:
    allow:
      - error
      - github\.com\/osamingo\/go-kenall\/v2\.ClientOption

linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      text: "does not use range value in test Run"
      linters:
        - paralleltest
    - path: _test\.go
      linters:
        - lll
        - err113
        - exhaustivestruct
        - cyclop
        - dupl
        - ifshort
        - varnamelen
        - containedctx
        - nosnakecase
        - exhaustruct
        - depguard
        - wsl
        - perfsprint
