linters-settings:
  errcheck:
    check-type-asserts: true
    check-blank: true
    ignore: io:^Copy.*
  misspell:
    locale: US

linters:
  enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      text: "does not use range value in test Run"
      linters:
        - paralleltest
    - path: _test\.go
      linters:
        - lll
        - goerr113
        - exhaustivestruct
        - cyclop
        - gochecknoglobals
