name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 10 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.2
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.16.x', '1.17.x' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...
        env:
          KENALL_AUTHORIZATION_TOKEN: ${{ secrets.KENALL_AUTHORIZATION_TOKEN }}
      - uses: codecov/codecov-action@v2
