name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '10 10 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37.0
  test:
    name: Test
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.15.x', '1.16.x' ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test Go Code
        run: go test -short -race -covermode=atomic -coverprofile=coverage.txt ./...
        env:
          KENALL_AUTHORIZATION_TOKEN: ${{ secrets.KENALL_AUTHORIZATION_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
